//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWebAPI.Reports.Online_Admission {
    
    public partial class StdColDtlOnlineAdmissionReport : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "StudentWebAPI.Reports.Online Admission.StdColDtlOnlineAdmissionReport.vsrepx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");

            // Parameters
            this.P_ORG_CODE = reportInitializer.GetParameter("P_ORG_CODE");
            this.P_STUDENT_CODE = reportInitializer.GetParameter("P_STUDENT_CODE");
            this.P_CAMPUS_CODE = reportInitializer.GetParameter("P_CAMPUS_CODE");
            this.P_COLLECTION_ID = reportInitializer.GetParameter("P_COLLECTION_ID");

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");
        }
        private DevExpress.XtraReports.Parameters.Parameter P_ORG_CODE;
        private DevExpress.XtraReports.Parameters.Parameter P_STUDENT_CODE;
        private DevExpress.XtraReports.Parameters.Parameter P_CAMPUS_CODE;
        private DevExpress.XtraReports.Parameters.Parameter P_COLLECTION_ID;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
    }
}
